shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - packages/vue/core
  - packages/vue/add-ons
  - playground/*
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - esbuild
  - vue-demi
